# Generated by Django 5.0.7 on 2024-07-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDekho_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
    ]
