# Generated by Django 5.2.2 on 2025-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atlantic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='checkin',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
