# Generated by Django 5.2.2 on 2025-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atlantic', '0002_remove_atendimento_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
