# Generated by Django 5.2.2 on 2025-06-11 12:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='atendimento_ptr',
        ),
        migrations.AddField(
            model_name='atividade',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.date(2025, 6, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='funcionario',
            field=models.ForeignKey(default=datetime.date(2025, 6, 11), on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='attendance.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
